version: "3"

services:
  techtalks.producer:
    image: moonstone.azurecr.io/mqproducer:rabbitmq-keda-3.1
    build:
      context: src
      dockerfile: Dockerfile-MQProducer

  techtalks.consumer:
    image: moonstone.azurecr.io/mqconsumer:rabbitmq-keda-3.1
    build:
      context: src
      dockerfile: Dockerfile-MQConsumer
